version: "3.1"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example 
      MYSQL_DATABASE: photobomb 
  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080
